apiVersion: v1
kind: Secret
metadata:
  name: vault-config
  namespace: argo-poc
type: Opaque
data:
  AVP_TYPE: vault
  AVP_AUTH_TYPE: token
  VAULT_NAMESPACE: argo-poc-vault
  VAULT_ADDR: http://vault-argo-internal:8200
  VAULT_TOKEN: CHANGEME
